### ISSUE TITLE
rendering時にリンク内の特殊記法をescapeできていない

### ISSUE THREAD

**Issue by takker99** [stakiran/monolithic#1]
リンク記法`[]()`内部の`|`などをテーブル記法として読み込んでしまっている

screenshot ([場所](https://stakiran.github.io/monolithic/3_communication_restraint.html#%E5%8F%82%E8%80%83))
[![Image from Gyazo](https://i.gyazo.com/3a9bfbde4b363932b30cc385e10525d0.png)](https://gyazo.com/3a9bfbde4b363932b30cc385e10525d0)

**Comment by stakiran** [comment]
## 報告ありがとうございます
そのうち修正しておきます。

## 現象
内部的なレンダリングエンジン Jekyll が `[★この中にパイプを含むパターン]()` に対応していない（あるいは markdown parserの仕様かもしれない）。パイプがあるからテーブルだと解釈されてしまっている。

ウェブサイトのタイトルには `|` で区切る物が多いので、よく起こる。

## 対処
パイプを使わない。

**Comment by stakiran** [comment]
## ✅コピー時に対処する案
https://scrapbox.io/sta/FormatLink#6168afbf79d3a90000cbeaa6

拡張機能で `[text](url)` をつくるときに、text中の` | `を` - `にreplaceする

## ビルド時に校正する案
textlint？みたいな路線。この処理だけなら自力でスクリ書いた方が早いかも

**Comment by stakiran** [comment]
修正した＆コピー時対処案を入れたので、いったんclose。

またしつこく発生するようなら、校正案を考える。
